use_frameworks!

target 'ImageMapView_Example' do
  pod 'AMPopTip', :git => 'https://github.com/kaich/AMPopTip.git'
  pod 'CKImageMap', :path => '../'

  target 'ImageMapView_Tests' do
    inherit! :search_paths

    
  end
end
